### ISSUE TITLE
error generating relationship between tables

### ISSUE THREAD

**Issue by CarlFMateus** [graphile-contrib/pg-many-to-many#21] opened 2019-09-02 13:06 UTC
Good afternoon, this is my problem. I have a table called talents within this table, there are two columns that relate to the city table, but it generates this error.
![Captura de pantalla de 2019-08-30 15-29-19](https://user-images.githubusercontent.com/46789400/64116571-4a5dfb00-cd58-11e9-9fa8-6392c56578c6.png)
I already made the respective intelligent comments to the foreign keys but the error still appears.
The relationship between the tables are these
![error](https://user-images.githubusercontent.com/46789400/64116592-606bbb80-cd58-11e9-837e-68b80ed532d1.jpeg)
What solution can you give me to this problem thanks.

**Comment by singingwolfboy** [comment] 2019-09-15 09:08
It looks like you used the `@manyToManyFieldName talent_plan` comment on two different constraints on the same table. This plugin is generating an error because it can't generate two different connections with the same name. You should be able to fix this problem by changing the smart comment for one of the constraints, so that it has a different name.

**Comment by mattbretl** [comment] 2019-09-20 21:23
I posted my original response here: https://github.com/graphile/postgraphile/issues/1149#issuecomment-526801560

I didn't understand your follow-up question here: https://github.com/graphile/postgraphile/issues/1149#issuecomment-527139917

To eliminate the error, I recommend removing that custom inflector code, which is the cause of the field name conflict. Let me know if you'd like help writing a custom inflector that will produce shorter, but still unique field names.

**Comment by mattbretl** [comment] 2020-02-13 07:45
[semi-automated message] Thanks for your question; hopefully we're well on the way to helping you solve your issue. This doesn't currently seem to be a bug in the library so I'm going to close the issue, but please feel free to continue the discussion.

**Closed by mattbretl** 2020-02-13 07:45 UTC

**Comment by CarlFMateus** [comment] 2020-03-06 14:05
I have already changed the name in the smart comment and I still see the error. The problem is that there are two columns that are related to the city table and those two columns are for the city where he was born and city of residence.
